// Code generated by entityrepo generator. DO NOT EDIT.
package [[ .PackageName ]]

import (
	"github.com/justclimber/fda/common/ecs/component"
	"github.com/justclimber/fda/server/worldprocessor/ecs/wpcomponent"
)

var (
    [[- range .ECGroups ]]
    [[ .MaskName ]] = component.NewMask([]component.Key{
        [[- range .Keys ]]
        [[ .FullStr ]],
        [[- end ]]
    })
    [[- end ]]
)
