// Code generated by entityrepo generator. DO NOT EDIT.
package [[ .PackageName ]]

import (
	"github.com/justclimber/fda/common/ecs/component"
	"github.com/justclimber/fda/common/ecs/entity"
	"github.com/justclimber/fda/server/worldprocessor/ecs/wpcomponent"
)
[[range .ECGroups ]]
type Entity[[ .MaskName ]] struct {
	Id       entity.Id
	[[- range .Keys ]]
    [[ .StrWithoutPrefix]] [[ .PackageName ]].[[ .StrWithoutPrefix ]]
    [[- end ]]
}
[[ end -]]

[[range .ECGroups ]]
func (e Entity[[ .MaskName ]]) EId() entity.Id       { return e.Id }
func (e Entity[[ .MaskName ]]) Mask() component.Mask { return [[ .MaskName ]] }
[[- end ]]
